### ISSUE TITLE
test with missing sensors

### ISSUE THREAD

**Issue by vladak** [vladak/weather#10]
`weather.py` should handle missing sensors gracefully.

**Comment by vladak** [comment]
When I disconnected the CO2 sensor (while running) the whole program exited due to:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/srv/weather/env/lib/python3.7/site-packages/adafruit_bus_device/i2c_device.py", line 154, in __probe_for_device
    self.i2c.writeto(self.device_address, b"")
  File "/srv/weather/env/lib/python3.7/site-packages/busio.py", line 166, in writeto
    return self._i2c.writeto(address, buffer, stop=stop)
  File "/srv/weather/env/lib/python3.7/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 49, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
  File "/srv/weather/env/lib/python3.7/site-packages/Adafruit_PureIO/smbus.py", line 314, in write_bytes
    self._device.write(buf)
OSError: [Errno 121] Remote I/O error
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/srv/weather/env/lib/python3.7/site-packages/adafruit_bus_device/i2c_device.py", line 160, in __probe_for_device
    self.i2c.readfrom_into(self.device_address, result)
  File "/srv/weather/env/lib/python3.7/site-packages/busio.py", line 156, in readfrom_into
    return self._i2c.readfrom_into(address, buffer, stop=stop)
  File "/srv/weather/env/lib/python3.7/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 56, in readfrom_into
    readin = self._i2c_bus.read_bytes(address, end - start)
  File "/srv/weather/env/lib/python3.7/site-packages/Adafruit_PureIO/smbus.py", line 181, in read_bytes
    return self._device.read(number)
OSError: [Errno 121] Remote I/O error
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/srv/weather/weather.py", line 66, in sensor_loop
    scd4x_sensor = adafruit_scd4x.SCD4X(i2c)
  File "/srv/weather/env/lib/python3.7/site-packages/adafruit_scd4x.py", line 97, in __init__
    self.i2c_device = i2c_device.I2CDevice(i2c_bus, address)
  File "/srv/weather/env/lib/python3.7/site-packages/adafruit_bus_device/i2c_device.py", line 50, in __init__
    self.__probe_for_device()
  File "/srv/weather/env/lib/python3.7/site-packages/adafruit_bus_device/i2c_device.py", line 163, in __probe_for_device
    raise ValueError("No I2C device at address: 0x%x" % self.device_address)
ValueError: No I2C device at address: 0x62
```
and had trouble starting. After I reconnected the sensor back, it started just fine.
