### ISSUE TITLE
deal with missing OWFS sensors

### ISSUE THREAD

**Issue by vladak** [vladak/weather#28]
After I disconnected one of the OWFS temperature sensors, the program refused to start again:

```
INFO:__main__:Running
DEBUG:__main__:Temperature sensor mappings: {'21f723030000': 'terasa', 'd5f2cf020000': 'kuchyne'}
DEBUG:__main__:outside temperature sensor: terasa
DEBUG:__main__:inside temperature sensor: kuchyne
DEBUG:__main__:Altitude = 245
DEBUG:__main__:Gauges: {'pressure': prometheus_client.metrics.Gauge(pressure_hpa), 'pressure_sea': prometheus_client.metrics.Gauge(pressure_sea_level_hpa), 'humidity': prometheus_client.metrics.Gauge(humidity_pct), 'CO2': prometheus_client.metrics.Gauge(co2_ppm), 'PM25': prometheus_client.metrics.Gauge(pm25), 'Lux': prometheus_client.metrics.Gauge(lux), 'TVOC': prometheus_client.metrics.Gauge(tvoc), 'terasa': prometheus_client.metrics.Gauge(weather_temp_terasa), 'kuchyne': prometheus_client.metrics.Gauge(weather_temp_kuchyne)}
INFO:__main__:Starting HTTP server on port 8111
INFO:__main__:Waiting for the first measurement from the SCD-40 sensor
DEBUG:__main__:lux=147
DEBUG:__main__:temperature sensors: {'21f723030000': 'terasa', 'd5f2cf020000': 'kuchyne'}
DEBUG:__main__:terasa temp=31.375
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/srv/weather/weather.py", line 93, in sensor_loop
    gauges, owfsdir, temp_sensors, temp_outside_name, temp_inside_name
  File "/srv/weather/weather.py", line 185, in acquire_temperature
    with open(file_path, "r", encoding="ascii") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/run/owfs/28.d5f2cf020000/temperature'

```

It probably crashed when the sensor was disconnected too.

**Comment by vladak** [comment]
The resolution will help #10.
